apiVersion: v1
kind: Service
metadata:
  name: vprocache01 #must latch the hostname given in the app porperties.
spec:
  selector:
    app: vpromc
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  type: ClusterIP
